### ISSUE TITLE
Specifying max solutions not working

### ISSUE THREAD

**Issue by stefanhannie** [coin-or/python-mip#32]
When passing in the optional parameter `max_solutions` to `Model.optimize()` I see the following output in the terminal

```
Welcome to the CBC MILP Solver 
Version: Trunk (unstable) 
Build Date: Oct 22 2019 
Revision Number: 2694 

command line - Cbc_C_Interface -max_solutions=1 -maxSavedSolutions=10 -integerT=1e-06 -solve -quit (default strategy 1)
No match for max_solutions - ? for list of commands
```

`max_solutions` should maybe be translated to `maxSo(lutions)`? (this is from `cbc` help prompt).

**Comment by h-g-s** [comment]
it should work with the new release  1.6  (released today), could you please check ?

**Comment by stefanhannie** [comment]
I think I'm still having the issue:
```
Welcome to the CBC MILP Solver 
Version: Trunk
Build Date: Nov 29 2019 

Starting solution of the Linear programming relaxation problem using Primal Simplex

Coin0506I Presolve 4548 (0) rows, 3136 (0) columns and 31552 (0) elements
Clp1000I sum of infeasibilities 5.43786e-07 - average 1.19566e-10, 632 fixed columns
Coin0506I Presolve 4548 (0) rows, 2504 (-632) columns and 11984 (-19568) elements
Clp0000I Optimal - objective value 8
Clp0000I Optimal - objective value 8
Coin0511I After Postsolve, objective 8, infeasibilities - dual 0 (0), primal 0 (0)
Clp0000I Optimal - objective value 8
Clp0000I Optimal - objective value 8
Clp0000I Optimal - objective value 8
Clp0032I Optimal objective 8 - 0 iterations time 0.212, Idiot 0.21

Starting MIP optimization
No match for max_solutions - ? for list of commands
```

**Comment by h-g-s** [comment]
Just tested now with 1.6.1  and it works fine, could you check ? :

Python 3.7.4 (/usr/bin/python)
>>> from mip import *
Using Python-MIP package version 1.6.1
>>> m = Model(solver_name="cbc")
>>> m.read('/home/haroldo/air04.mps')
Coin0008I air04 read with 0 errors
>>> m.max_solutions = 1
>>> m.optimize()
Welcome to the CBC MILP Solver
Version: Trunk
Build Date: Nov 29 2019

Starting solution of the Linear programming relaxation problem using 
Primal Simplex

Coin0506I Presolve 645 (-178) rows, 7920 (-984) columns and 53032 (-19933) 
elements
Clp1000I sum of infeasibilities 0.00171603 - average 2.66051e-06, 7117 
fixed columns
Coin0506I Presolve 411 (-234) rows, 764 (-7156) columns and 3762 (-49270) 
elements
Clp0029I End of values pass after 746 iterations
Clp0014I Perturbing problem by 0.001% of 1.0000001 - largest nonzero 
change 2.9925651e-05 ( 0.0014962825%) - largest zero change 2.95206e-05
Clp0000I Optimal - objective value 55547.038
Clp0000I Optimal - objective value 55547.038
Coin0511I After Postsolve, objective 55547.038, infeasibilities - dual 0 
(0), primal 0 (0)
Clp0014I Perturbing problem by 0.001% of 1 - largest nonzero change 
2.9934324e-05 ( 0.0014967162%) - largest zero change 2.95206e-05
Clp0000I Optimal - objective value 55535.436
Clp0000I Optimal - objective value 55535.436
Clp0000I Optimal - objective value 55535.436
Coin0511I After Postsolve, objective 55535.436, infeasibilities - dual 0 
(0), primal 0 (0)
Clp0032I Optimal objective 55535.43639 - 0 iterations time 0.382, Presolve 
0.03, Idiot 0.35

Starting MIP optimization
maxSavedSolutions was changed from 0 to 10
integerTolerance was changed from 1e-06 to 1e-06
Continuous objective value is 55535.4 - 0.01 seconds
Cgl0003I 382 fixed, 0 tightened bounds, 0 strengthened rows, 1 
substitutions
Cgl0003I 23 fixed, 0 tightened bounds, 0 strengthened rows, 0 
substitutions
Cgl0003I 2 fixed, 0 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 3 fixed, 0 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 735 rows, 8462 columns (8462 integer (8462 of 
which binary)) and 64927 elements
Cutoff increment increased from 1e-05 to 0.9999
Cbc0038I Initial state - 290 integers unsatisfied sum - 51.0753
Cbc0038I Pass   1: suminf.    8.60000 (26) obj. 58333.1 iterations 4997
Cbc0038I Pass   2: suminf.    4.00000 (8) obj. 58972.5 iterations 160
Cbc0038I Pass   3: suminf.    4.00000 (8) obj. 58972.5 iterations 18
Cbc0038I Pass   4: suminf.    4.00000 (8) obj. 58972.5 iterations 413
Cbc0038I Pass   5: suminf.    0.00000 (0) obj. 59389 iterations 140
Cbc0038I Solution found of 59389
Cbc0038I After 2.56 seconds - Feasibility pump exiting with objective of 
59389 (stopping after 1 solutions) - took 1.75 seconds
Cbc0012I Integer solution of 59389 found by feasibility pump after 0 
iterations and 0 nodes (2.56 seconds)
Cbc0019I Exiting on maximum solutions
Cbc0005I Partial search - best objective 59389 (best possible 55535.436), 
took 0 iterations and 0 nodes (2.56 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 55535.4 to 55535.4
Probing was tried 0 times and created 0 cuts of which 0 were active after 
adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after 
adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after 
adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after 
adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were 
active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active 
after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active 
after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after 
adding rounds of cuts (0.000 seconds)

Result - Stopped on solution limit

Objective value:                59389.00000000
Lower bound:                    55535.436
Gap:                            0.07
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             2.59
Time (Wallclock seconds):       2.64

Total time (CPU seconds):       2.59   (Wallclock seconds):       2.64

<OptimizationStatus.FEASIBLE: 3>


-- 
=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
email: haroldo@ufop.edu.br
        Haroldo.GambiniSantos@cs.kuleuven.be
home/research page: www.decom.ufop.br/haroldo


It has long been an axiom of mine that the little things are infinitely
the most important.
-- Sir Arthur Conan Doyle, "A Case of Identity"

**Comment by stefanhannie** [comment]
Nice! Thanks for the working example. Your method above works for me. 

What I was doing is still not working though. I was calling 
```python
m = mip.Model()
m.optimize(max_solutions=1)
```

Sorry. I should have put that at the beginning of the issue.

**Comment by h-g-s** [comment]
Hmm, forgot that it could be specified as parameter in cbc. Fixed, 
released version 1.6.2 with the fix.

-- 
=============================================================
Haroldo Gambini Santos
Computing Department
Universidade Federal de Ouro Preto - UFOP
email: haroldo@ufop.edu.br
        Haroldo.GambiniSantos@cs.kuleuven.be
home/research page: www.decom.ufop.br/haroldo


It has long been an axiom of mine that the little things are infinitely
the most important.
-- Sir Arthur Conan Doyle, "A Case of Identity"

**Comment by stefanhannie** [comment]
Works! Thanks for the fix.
